name: CI Pipeline for docker
on: 
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v6
            - name: Test checkout
              run: ls
            - name: Build docker
              run: docker build -t test/app:latest .
            - name: Test docker
              run: docker images
    push:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - run: echo "Pushin"
